require: 
  - rubocop-capybara
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - '*.lock'
    - '.git/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'bin/**/*'
    - 'tmp/**/*'

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120
  Exclude:
    - 'config/initializers/*'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'

Style/FrozenStringLiteralComment:
  Exclude:
    - 'db/**/*'
    

RSpec/ExampleLength:
  Exclude:
    - 'spec/system/**/*'
