# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `NotificationTestMailer`.
# Please instead update this file by running `bin/tapioca dsl NotificationTestMailer`.

class NotificationTestMailer
  class << self
    sig { params(user: T.untyped).returns(::ActionMailer::MessageDelivery) }
    def notification(user); end
  end
end
