# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: false

module Devise::ConfirmationsController; end
module Devise::OmniauthCallbacksController; end
module Devise::PasswordsController; end
module Devise::RegistrationsController; end
module Devise::SessionsController; end
module Devise::UnlocksController; end
